version: '3.8'

services:
  app:
    container_name: ${DOCKER_CONTAINER_NAME}
    restart: always
    build:
      context: ../app
      dockerfile: nodejs.Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - ../app:/usr/src/app/
      - /usr/src/app/node_modules