version: '3.8'

services:
  app:
    container_name: ${DOCKER_IMAGE_NAME}
    restart: always
    build:
      context: ../app
      dockerfile: app.Dockerfile
    image: ${DOCKER_IMAGE_NAME}
    ports:
      - "3000:8080"
    volumes:
      - ../app:/usr/src/app/
      - /usr/src/app/node_modules